### ISSUE TITLE
README should link to readthedocs...

### ISSUE THREAD

**Issue by steveri** [cornell-brg/mflowgen#14]
I keep forgetting where the user guide is (https://mflowgen.readthedocs.io). Shouldn't there be a prominent link to it somewhere high up in the mflowgen README (https://github.com/cornell-brg/mflowgen/blob/master/README.md)?

**Comment by ctorng** [comment]
You can actually click the green badge.

**Comment by steveri** [comment]
Hm looks like a lot of duplicated effort in README vs. io docs. Seems like most of the README could be replaced by hyperlinks to the user guide. Or at the very least the README could have an occasional (or at least one) 'more info can be found [here](https://mflowgen.readthedocs.io/en/latest/quick-start.html)'

All of this is my long-winded way of saying "oops I looked all over that page and somehow never noticed the stupid badge" :(

**Comment by ctorng** [comment]
That's because the readthedocs just popped up very recently, and the README content is transferring over to there... :) So right now there is some content in one and not the other and vice versa.

The README will eventually be shorter. I'll add a more info can be found here at the end of it. Thanks!
