### ISSUE TITLE
integerate the freePDK15

### ISSUE THREAD

**Issue by shenjiangqiu** [cornell-brg/mflowgen#66]
Is there a plan to add freePDK15 support for mflowgen?

**Comment by ctorng** [comment]
Sorry.. I missed this notification.

We haven't had anyone working on FreePDK15, so that's why it is not included right out of the box. Currently most mflowgen users to my knowledge are working through commercial technologies and have set up their own ADKs internally (fairly simple using freepdk-45nm as a reference).

Looking ahead, I think it would be useful to have FreePDK15 and ASAP7 shipped out of the box, but we just don't have the hands to do this right now.

By the way there is great interest in SkyWater130, which hopefully opens many doors in the open-source world for manufacturable designs:

- https://github.com/google/skywater-pdk

There are plans to integrate this into mflowgen.
